name = "AlgebraicDataMigrations"
uuid = "0c4ad18d-0c49-4bc2-90d5-5bca8f00d6ae"
license = "MIT"
authors = ["AlgebraicJulia Developer <email@algebraicjulia.org>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[compat]
Catlab = "^0.14"
julia = "1.10"
