name = "AlgebraicDataMigrations"
uuid = "0c4ad18d-0c49-4bc2-90d5-5bca8f00d6ae"
license = "MIT"
authors =  ["Kevin Arlin <kevin@topos.institute",
            "Evan Patterson <evan@topos.institute>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ACSets = "227ef7b5-1206-438b-ac65-934d6da304b8"
MLStyle = "d8e11817-5142-5d16-987a-aa16d5891078"

[compat]
ACSets = "0.2.5"
Catlab = "0.15"
julia = "1.10"
MLStyle = "0.4"