env:
  JULIA_VERSION: "1.10.2"
  GATAS_HOME: "~/.gatas/buildkite/agents/$BUILDKITE_AGENT_NAME"

steps:

  - label: ":hammer: Build Project"
    env:
      JULIA_DEPOT_PATH: "$GATAS_HOME"
    commands: 
      - "module load julia"
      - "julia --project=docs --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.precompile()'"
         
  - wait 

  - labels: ":scroll: Build docs and run tests"
    env:
      JULIA_DEPOT_PATH: "$GATAS_HOME/$BUILDKITE_AGENT_NAME"
      JULIA_PROJECT: "docs/"
    command:
      - "srun --cpus-per-task=16 --mem=64G --time=1:00:00 --output=.buildkite/build_%j.log --unbuffered .buildkite/jobscript.sh"

  - wait

