name: Julia CI
on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        description: "Token for the repository from codecov.io for uploading the code coverage report"
        required: false
    inputs:
      codecov:
        description: "Whether or not to include codecov"
        default: true
        required: false
        type: boolean
      docs:
        description: "Whether or not to build and deploy Documenter.jl docs"
        default: true
        required: false
        type: boolean
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: # use matrix notation for linux for easily testing more versions/architectures
        version: ["1.10.0-beta2"]
        os: [ubuntu-latest]
        arch: ["x64"]
        include:
          # test macOS and Windows with latest Julia only
          - os: macOS-latest
            arch: x64
            version: "1.10.0-beta2"
          - os: windows-latest
            arch: x64
            version: "1.10.0-beta2"

    steps:
      - uses: actions/checkout@v3
      - name: "Install Graphviz"
        uses: ts-graphviz/setup-graphviz@v1
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - name: "Run tests"
        uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
        if: ${{ inputs.codecov }}
      - uses: codecov/codecov-action@v3
        if: ${{ inputs.codecov }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
